# Simple demo script for running CodeCov on each push to develop/a PR that 
# is merging into develop. All steps other than "Upload coverage reports to Codecov"
# are currently implemented in evergreen, but duplicated here for convenience.
name: Run CodeCov

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - develop

env:
  BUILD_TYPE: Coverage

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: build wiredtiger
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: | 
        cd ${{github.workspace}}/build/examples
        ctest -C ${{env.BUILD_TYPE}}

        cd ${{github.workspace}}/build/test/csuite
        ctest -j 8 -R "(2695|3363|3120|3874|2592|4117|2447|2447|9937|4699|4891|4156|4105|2403)"

        cd ${{github.workspace}}/build/test/readonly
        ctest -j 8

        cd ${{github.workspace}}/build/test/cursor_order
        ctest -j 8

        cd ${{github.workspace}}/build/test/bloom
        ctest -j 8

        cd ${{github.workspace}}/build/test/packing
        ctest -j 8

    - name: Generate code coverage report
      working-directory: ${{github.workspace}}
      run: |
        sudo apt-get -y install gcovr
        gcovr --gcov-ignore-parse-errors --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${{github.workspace}}
  
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
          gcov: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
