name: Greeter

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |

            const pr_creator = context.payload.sender.login

            wt_members = "fixme"
            github.rest.orgs.listMembers({
              org: "wiredtiger"
            })



            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hello ' + pr_creator + '!' + " members? " + wt_members
            })
