name: Greeter

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr_creator = context.payload.sender.login
            const wt_members = await github.rest.orgs.listMembers({ org: "wiredtiger"})
              .then((results) => results.data.map((user) => user.login));

            # github.rest.issues.createComment({
            #   issue_number: context.issue.number,
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            #   body: 'Hello ' + pr_creator + '!' + " members? "
            # })

  # Disable - some parsing issues I'm not in the mood to deal w/ right now
  # pr-title-check:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pull-requests: write
  #   steps:
  #     - uses: actions/github-script@v6
  #       with:
  #         github-token: ${{secrets.GITHUB_TOKEN}}
  #         script: |
  #           pr_title = context.payload.pull_request.title

  #           # regex not supported. We're going hacky
  #           is_valid = false
  #           first_word = pr_title.split(' ')[0]
  #           if (first_word).startsWith("WT-")) {
  #             ticket_num = first_word.split('-')[1]
  #             if(Number.isInteger(ticket_num)) {
  #               is_valid = true
  #             }
  #           }
            
  #           if (is_valid) {
  #             github.rest.issues.createComment({
  #               issue_number: context.issue.number,
  #               owner: context.repo.owner,
  #               repo: context.repo.repo,
  #               body: 'Please fix your title to begin with a WT ticket followed by a space: e.g. "WT-1000 Example text"'
  #             })
  #           }
